### PR TITLE
Activating Open Collective

### PR DESCRIPTION
**Pull request by monkeywithacupcake**
Hi, I'm making updates for Open Collective. Either you or a supporter signed this repo up for Open Collective. This pull request adds backers and sponsors from your Open Collective https://opencollective.com/sit ❤️
  
  It adds two badges at the top to show the latest number of backers and sponsors. It also adds placeholders so that the avatar/logo of new backers/sponsors can automatically be shown without having to update your README.md. [[more info](https://github.com/opencollective/opencollective/wiki/Github-banner)]. See how it looks on [this repo](https://github.com/apex/apex#backers).
You can also add a "Donate" button to your website and automatically show your backers and sponsors there with our widgets. Have a look here: https://opencollective.com/widgets

  P.S: As with any pull request, feel free to comment or suggest changes. The only thing "required" are the placeholders on the README because we believe it's important to acknowledge the people in your community that are contributing (financially or with code!).

  Thank you for your great contribution to the open source community. You are awesome! 🙌
  And welcome to the open collective community! 😊

  Come chat with us in the #opensource channel on https://slack.opencollective.com - great place to ask questions and share best practices with other open source sustainers!

### CODE REVIEW

**Comment by Serkan-devel** [comment]
This PR seems fishy to me. Haven't you even taken the time to actually read their readme and their [contributing guidelines](https://github.com/sit-fyi/sit/blob/master/CONTRIBUTING.md)? Not even the first sentence on it?

**Comment by yrashk** [comment]
@Serkan-devel Thank you for your comment. I believe this is an automated PR from Open Collective. Though I tried to set up this new collective quite some time ago, it looks like this PR has only been sent today. For now I've abandoned the attempt to use Open Collective. I've used it before for another project, but it looks like the site is a lot buggier now so I wasn't sure if I want to continue with them. 

(That said, I am still looking for ways to raise funds for the project to focus on it full-time!)

**Comment by monkeywithacupcake** [comment]
I think there are a lot of changes in Open Collective to adapt ot changing needs of collectives. You can keep the bare bones if you want (like a link in the readme or maybe in an issue template to remind users especially those filing issues that you are open source and taking donations) and delete the rest - to keep it light. However, if it does not work for you or your team to have Open Collective, that's okay, too. 

FWIW - I do read contributing guidelines, but I am also using the Open Collective command line setup tool to ensure that the code is consistent from one repo to another and avoid typos. Since it automates the PR (a time saver for me), I can see how it looks a little wonky.
 
Best of luck!

**Comment by dumblob** [comment]
@yrashk, @stuarth, @dysinger, @coder543, @vks, @lessless, @sit-bot

OT: As a newcomer to this project, I followed all instructions, downloaded the last released version of SIT with a sole goal to post few issues (questions mainly and some comments on the architecture and decisions). During compilation there were few warnings, but it compiled. After running `sit` there was first glitch - no newline at the end. Running `sit-web` show a web page with `No web overlay defines an application.`. Running `sit items` results in panic:

```rust
$ git clone https://github.com/sit-fyi/sit.git
...
$ cd sit
$ sit items
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Os { code: 2, kind: NotFound, message: "No such file or directory" })', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

This convinced me, that disallowing `Issues` on GitHub is a **really bad idea** as it

1. completely disallows asking any important questions about the project (mind that you have only a workflow for *Problems with Solutions*, but no communication platform in the first place!),

2. mitigates contributions from anyone who threw away the standard GitHub procedure, read and learned a completely new one (including technical architectural details how SIT works and how does the decoupling from SCMs look like, etc.), then finally got through the hassle of getting Rust to run on her platform, then finally tried to compile SIT, and in the end `sit` panics.

This overall could really be nominated to the most frustrating experience competition among GitHub projects :cry:.

So, could you please do us, newcomers, a favor and

1. let GitHub Issues be created (preferably with a default template for a Question and a strong notice, that any other Issues shall be done through SIT),

2. release a version which is really well tested for all the workflows you'd like everyone to follow (i.e. those described in all the instructions and READMEs and *.md files)?

@monkeywithacupcake apologies for using your pull here for this OT purpose.

**Comment by yrashk** [comment]
Hi,

Sorry for this experience! The project is on hiatus (I'm figuring out my
next steps based on my learnings). I'm away from my computer right now, but
I can tell that sit-web error comes from not having git submodules updated.
Looks like the instructions don'ts mention this. Sorry about that.

I'll update the project to make it visible that it's on hiatus.

**Comment by yrashk** [comment]
...and thanks for the rest of the feedback -- it is most valuable!

**Pull request closed without merging**
