### PR TITLE
Added issue

### PR DESCRIPTION
**Pull request by vks**

### CODE REVIEW

**Comment by yrashk** [comment]
Great issue. I've actually thought about it at the very start. But we need `Commented` record type in SIT to discuss this issue there (to preserve the history!). Putting this as a top-priority :)

**Comment by vks** [comment]
Yeah, discussing would be super painful unfortunately, with one pull request per comment. Maybe have [some bot](https://bors.tech/) automatically merge them?

**Comment by yrashk** [comment]
Yes, I think we need an issue merging bot! That's a great idea. Could also
operate over email, or just scan PRs.

**Comment by yrashk** [comment]
Comments fall under that description because they always add new records

On Jan 30, 2018 9:03 AM, "Vinzent Steinberg" <notifications@github.com>
wrote:

Comments should be allowed as well. But yes, that is what I was thinking.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/sit-it/sit/pull/27#issuecomment-361661719>, or mute the
thread

**Comment by yrashk** [comment]
Comments are in! I've commented on this issue there.

**Comment by yrashk** [comment]
Tracking the merge bot idea in a3df42f7-abe6-42b8-8ec8-1db14d966ad4

**Comment by yrashk** [comment]
I've enabled automatic merging of records! Check this out https://github.com/sit-it/sit#send-it-to-upstream

**Pull request merged**
